nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: BileMo est une entreprise spécialisée dans les téléphones mobiles haut de gamme, offrant une large sélection de produits
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
